server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://hopper.proxy.rlwy.net:55486/railway?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: sKCZTiAyWfhxnoXCQxaYLVGcxbKsYbwU
  jpa:
    hibernate:
      ddl-auto: update
